DROP TABLE IF EXISTS pedidos;


CREATE TABLE pedidos (
id VARCHAR(255) PRIMARY KEY NOT NULL,
payment_id VARCHAR(255) UNIQUE,
status_pagamento ENUM ("approved", "pending", "rejected") NOT NULL DEFAULT 'pending',
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
cpf VARCHAR(50) NOT NULL,
telefone VARCHAR(50) NOT NULL,
endereco VARCHAR(255) NOT NULL,
numero  VARCHAR(11) NOT NULL,
bairro VARCHAR(255) NOT NULL,
complemento VARCHAR(255),
cidade VARCHAR(255) NOT NULL,
estado VARCHAR(255) NOT NULL,
cep VARCHAR(50) NOT NULL,
data_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

